pool: MyHost

trigger: none 

stages:
- stage: PreCommit
  displayName: Pre-Commit / Static Analysis Stage
  pool: MyHost
  jobs: 
  - job: Terraform_Install_Validate
    displayName: Terraform_Install_Validate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'dev-service-connection'
        backendAzureRmStorageAccountName: 'kumamrig1234567890'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

  - job: TerraformFmt
    dependsOn: TerraformValidate
    displayName: Terraform Fmt
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        environmentServiceNameAzureRM: 'dev-service-connection'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        outputTo: 'console'
        customCommand: 'fmt'

  - job: tfsec
    dependsOn: TerraformFmt
    displayName: TfSec Scan
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/env/dev'

  - job: tflint
    dependsOn: tfsec
    displayName: TFLint
    steps:
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          winget install TerraformLinters.tflint     
          ls   
          tflint
        errorActionPreference: 'continue'        
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

- stage: costStage
  dependsOn: PreCommit
  displayName: Cost & Impact Assessment Stage
  jobs: 
  - job: InfraCost
    displayName: InfraCost
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'infracost breakdown --path=.'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

- stage: plan
  displayName: Plan & Review Stage
  jobs: 
  - job: TerraformPlan
    displayName: Terraform Plan
    pool: MyHost
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'dev-service-connection'
        backendAzureRmStorageAccountName: 'kumamrig1234567890'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'dev-service-connection'

- stage: approval
  dependsOn: plan
  displayName: Approval & Governance Stage
  jobs:
  - job: ManualApproval
    displayName: Manual Approval
    pool: server
    steps: 
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'falana@gmail.com'

- stage: apply
  dependsOn: approval
  displayName: Deploy / Apply Stage
  jobs:
  - job: TerraformApply
    displayName: Terraform Apply
    pool: MyHost
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'dev-service-connection'
        backendAzureRmStorageAccountName: 'kumamrig1234567890'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'dev-service-connection'
